In [1]:
import numpy as np

In [2]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [4]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.random.randint((10,10))

array([3, 2], dtype=int32)

In [7]:
np.linspace(10,21,10)

array([10.        , 11.22222222, 12.44444444, 13.66666667, 14.88888889,
       16.11111111, 17.33333333, 18.55555556, 19.77777778, 21.        ])

In [10]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
np.ndim(a1)

2

In [11]:
a1.size

8

In [13]:
a1.dtype

dtype('int64')

In [14]:
a1 =  np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)

In [17]:
np.ndim(a2)

2

In [18]:
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a2.flatten()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [20]:
a1 =  np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)

In [21]:
a1 * 2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [23]:
a1>9

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [24]:
np.sum(a1)
np.mean(a1)
np.median(a1)
np.min(a1)
np.max(a1)
np.var(a1)
np.std(a1)


np.float64(3.452052529534663)

In [25]:
a1 =  np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [26]:
a1[-1]

array([ 8,  9, 10, 11])

In [29]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
print(a1[0:1])

[[0 1 2 3]]


In [38]:
a1[0,:]

array([0, 1, 2, 3])

In [36]:
a1[2:5:2]

array([[ 8,  9, 10, 11]])

In [37]:
a2[0,:]

array([12, 13, 14, 15])

In [39]:
a2[0:2,1:3]

array([[13, 14],
       [17, 18]])

In [40]:
a2[::2,::3]

array([[12, 15],
       [20, 23]])

In [42]:
a2[:,2] # all rows and only 2nd column

array([14, 18, 22])

In [43]:
for i in a2:
    print(i)

[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [44]:
for i in np.nditer(a2):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


In [45]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a2.T

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [48]:
a2.transpose()

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [49]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(3,4)

In [51]:
np.hstack((a2,a3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

#### Practice Questions

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**
- Create a null vector of size 10 but the fifth value which is 1.

In [52]:
import numpy as np
a = np.nan  * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [61]:
x, y = map(int, input().split())
x = np.random.random((x,y))
print(x)
print(x.mean())


[[0.65829661 0.66586919 0.04113941 0.14884026 0.31910555]
 [0.48571022 0.77762338 0.79640438 0.21272786 0.17853178]]
0.4284248627270267


`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [64]:
def border_array(a,b):
    x = np.ones((a,b))
    x[1:-1,1:-1]= 0
    return x
border_array(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [66]:
x = np.linspace(0,1,12)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Can you create a identity matrix of shape (3,4). If yes write code for it.

In [67]:
# Nope u cannot create a identity matrix of 3,4. It will always be a square matrix
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 5x5 matrix with row values ranging from 0 to 4.

In [76]:
a = np.zeros((5,5))
a += a + np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

point = np.array([2,3])

In [77]:
a = np.random.randint(1,100,(10,2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis = 1)).astype(int)

array([103,  61, 108,  19,  96, 127,  42,  65,  26,  42])

Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [81]:
a = np.unravel_index(100,(6,7,8))
print(a)

(np.int64(1), np.int64(5), np.int64(4))


**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [82]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

array([6., 5., 2.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [83]:
a = np.array([])
a = np.array([1,2])
a.size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```