In [2]:
import numpy as np

#### 0D Tensor

In [ ]:
n = np.array(4)

In [4]:
n

array(4)

In [5]:
n.ndim

0

#### 1D Tensor
- Also called Vector
- This is 1D Tensor also a vector with 4 dimension(for vector it had 4dimension)

In [10]:
a = np.array([1,2,3,4])
a.ndim

1

#### 2D Tensor
- Also called `matrics`

In [11]:
mat = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
mat.ndim

2

In [7]:
a = np.arange(2,8).reshape(2,3)

In [9]:
a.ndim

2

### Vectors


In [13]:
import numpy as np


In [ ]:
# distance from origin -> euclidean distance
# n-dimension vector A
A = np.array([1,2,3,4,5])
# finding euclidean distance
distance = np.linalg.norm(A)
print("Euclidean distance from origin: ", distance)

Euclidean distance from origin:  7.416198487095663


In [ ]:
# wrong answer
A = np.array([1,2,3,4,5])
distance = sum(np.sqrt(A))
print("Euclidean distance from origin: ", distance)

Euclidean distance from origin:  8.382332347441762


In [17]:
# Euclidean distance for 2 n-dimension vectors A and B
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])
difference = A - B
distance = np.linalg.norm(difference)
print("Euclidean distance between A and B: ", distance)


Euclidean distance between A and B:  11.180339887498949


### Dot Product
- Scalar
- It is commutative A.B = B.A
- It is Distributive A.(B+C) = A.B + A.C

In [ ]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.dot(A,B))


32


# Cosine Similarity

In [21]:
A = np.array([1,2,3])
B = np.array([-4,-5,-6])
C = np.array([5,5,5])
cosine_similarity = np.dot(A,B)/ (np.linalg.norm(A)*np.linalg.norm(B))
print("Cosine similarity of A and B: ", cosine_similarity)

cosine_similarity = np.dot(A,C)/(np.linalg.norm(A)*np.linalg.norm(C))
print("Cosine similarity of A and C :", cosine_similarity)

Cosine similarity of A and B:  -0.9746318461970762
Cosine similarity of A and C : 0.9258200997725513


### Matrix

In [22]:
import numpy as np
A = np.array([[1,3,4],[6,4,1],[2,2,2]])
A

array([[1, 3, 4],
       [6, 4, 1],
       [2, 2, 2]])

In [23]:
B = np.array([5,16,11])
B

array([ 5, 16, 11])

In [24]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.75 , -0.25 ,  1.625],
       [ 1.25 ,  0.75 , -2.875],
       [-0.5  , -0.5  ,  1.75 ]])

In [28]:
np.dot(A_inv,B)

array([ 10.125, -13.375,   8.75 ])