In [1]:
!pip install numpy

In [2]:
import numpy as np


In [3]:
lst = [1,2,3,4]
arr = np.array(lst)
print(arr)

[1 2 3 4]


In [4]:
##Creating Multidimensional Arrays


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr = np.arange(1,10,2)


In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

print('Total : ', arr.size)
print('Rows  : ', np.size(arr,0))
print('Cols  : ', np.size(arr,1))

Total :  12
Rows  :  4
Cols  :  3


In [7]:
##Shape Function :  It used to find the dimensions of data ie no of rows and columns


arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr.shape)

(4, 3)


In [8]:
arr1 = np.array([1,2,3,1,2,3])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1.ndim)
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3.ndim)

1
2
3


In [10]:
##Ndim Function :The ndim attribute in NumPy provides the number of dimensions in an array ie 1-D , 2-D etc.


arr1 = np.array([1,2,3,1,2,3])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1.ndim)
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3.ndim)

1
2
3


In [11]:
import numpy as np
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])