### Starting with the numpy Libraries
- numpy are faster as compared to simple array, because they directly fetch the value

In [14]:
import numpy as np

In [15]:
# 1d array = vector
np.array([10,10,20,30])

array([10, 10, 20, 30])

In [16]:
#2d array = matrix
np.array([[10,20,30,40],[2,3,4,5]])

array([[10, 20, 30, 40],
       [ 2,  3,  4,  5]])

In [17]:
#3s array = tensor
np.array([[[10,20,30,40],[2,3,4,5]],[[5,6,7,8],[5,9,6,7]]])


array([[[10, 20, 30, 40],
        [ 2,  3,  4,  5]],

       [[ 5,  6,  7,  8],
        [ 5,  9,  6,  7]]])

In [18]:
type(np.array([[[10,20,30,40],[2,3,4,5]],[[5,6,7,8],[5,9,6,7]]]))
#output shows that it is an array of n dimensional

numpy.ndarray

In [19]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [20]:
#A range

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
# reshaping the array, 1d to 2d
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
np.arange(1,26).reshape(5,5)
#Will throw value error 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
#To find the dimensional of an array
np.ndim(np.arange(1,11,2))
np.ndim(np.arange(1,11).reshape(2,5))

2

### Method to change of an array from one dimensional to another
- Using the .reshape

In [24]:
size=12
100,120
np.arange(100,120).reshape(2,10)


array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [25]:
np.ndim(np.arange(100,120).reshape(2,10))

2

In [26]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.random.random((10))

array([0.4878929 , 0.57154247, 0.23599376, 0.45414644, 0.30460649,
       0.59621131, 0.81377909, 0.57922432, 0.91995655, 0.59828284])

In [52]:
np.random.randint((10,10))
np.random.randint((10,10,10))

array([4, 9, 6])

In [30]:
np.linspace(-10,10,10)
#It is generating -10 to 10 values with same space 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [31]:
np.identity(10)
#Generating an identity matrix, having the same diagonal values

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
n1 = np.arange(10)
n2 = np.arange(10,20).reshape(2,5)
n3 = np.arange(100,150).reshape(5,10)
n4 = np.arange(10,70).reshape(2,3,10)
print(n1)
print('-'*90)
print(n2)
print('-'*90)
print(n3)
print('-'*90)
print(n4)
np.ndim(n4)

[0 1 2 3 4 5 6 7 8 9]
------------------------------------------------------------------------------------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
------------------------------------------------------------------------------------------
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
------------------------------------------------------------------------------------------
[[[10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]]]


3

In [33]:
r1 = np.arange(10,70).reshape(3,2,10)
# no of array, row size, column size
print(a1)

NameError: name 'a1' is not defined

In [ ]:
r2 = np.arange(10,110).reshape(2,5,10)
print(a2)
#Here i have 2 array with 5 rows and 10 columns

[[[ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]]]


### Array Operations

In [ ]:
a1 =  np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Arithmetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#relational 
a2 >15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#Doing vector operations
a1 + a2
#Shape should be similar of both the array while doing the arithmetic operations

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1.min()

0

In [ ]:
a1.max()


11

In [ ]:
a2.max()

23

In [ ]:
a2.sum()

210

In [ ]:
a2.prod()

816826368

### Sin/ Cos/ Tan

In [ ]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
np.cos(a2)

array([[ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302]])

In [ ]:
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [ ]:
np.mean(n1)

4.5

In [ ]:
np.median(a1)

5.5

In [ ]:
np.mod(a1,2)
#remainder part

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [ ]:
np.var(a1)

11.916666666666666

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.max(a1, axis = 0)
#axis =0 is for rows

array([ 8,  9, 10, 11])

In [ ]:
np.max(a1, axis =1)

array([ 3,  7, 11])

In [ ]:
#getting values in exponential format
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#for round of the values
np.round(np.random.random((2,3))*100)

array([[ 38.,  90., 100.],
       [ 28.,  23.,  62.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[90., 52., 16.],
       [48., 33., 95.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[90., 71., 65.],
       [98., 52., 14.]])

### Indexing and slicing

In [34]:
a1  = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [35]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a2[:,2]

array([ 2,  6, 10])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2[0,2]

2

In [39]:
a2[2,3]

11

In [40]:
a2[(1,1),(1,2)]
#here array is extracted but dimension is changed

array([5, 6])

In [41]:
a2[1:2,1:3]
#Here dimension is not changed

array([[5, 6]])

In [42]:
a2[((1,1),(1,2)),((1,2),(2,2))]
#In efficiency to fetch 5,6,9,10

array([[ 5,  6],
       [ 6, 10]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Using step count

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#fetching 5,7,9,11
a2[1:,1::2 ]

array([[ 5,  7],
       [ 9, 11]])

In [ ]:
#fetching 1,3,9,11
a2[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1:2,::2]

array([[4, 6]])

In [ ]:
a2[0:3:2,1::3]

array([[1],
       [9]])

#### Fancy indexing

In [ ]:
a2[[0,2],[0,3]]

array([ 0, 11])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[[1, 1, 2, 2], [1, 3, 1, 3]]


array([ 5,  7,  9, 11])

In [ ]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,1]

3

### Stacking 

In [44]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(3,4)

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### horizontal stacking

In [47]:
np.hstack((a2,a3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### Vertical stacking

In [48]:
np.vstack((a2,a3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Splitting

In [49]:
np.hsplit(a2,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [50]:
np.vsplit(a2,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### Advance Numpy

In [59]:
# Time taken by array in this code
a = [i for i in range(1000000)]
b = [i for i in range(1000000,2000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

0.1527402400970459


In [60]:
# numpy
a = np.arange(1000000)
b = np.arange(1000000,2000000)
start = time.time()
c.append(a+b)
print(time.time()-start)

0.002982616424560547


## Broadcasting 
- taking the matrix with different shape and tranforming it into a single one with the help of copying and then doing operations in it.

In [61]:
# same shape
a  = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print("-"*90)
print(b)
print("-"*90)
print(a+b)
print("-"*90)


[[0 1 2]
 [3 4 5]]
------------------------------------------------------------------------------------------
[[ 6  7  8]
 [ 9 10 11]]
------------------------------------------------------------------------------------------
[[ 6  8 10]
 [12 14 16]]
------------------------------------------------------------------------------------------


In [62]:
# diff shape
a  = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print("-"*90)
print(b)
print("-"*90)
print(a+b)

[[0 1 2]
 [3 4 5]]
------------------------------------------------------------------------------------------
[[0 1 2]]
------------------------------------------------------------------------------------------
[[0 2 4]
 [3 5 7]]


In [63]:
a  = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(3)
print(a+b)

[[0 2 4]
 [3 5 7]]


In [66]:
#doing product in here
a  = np.arange(4).reshape(4,1)
b = np.arange(12).reshape(4,3)
print(a)
print("-"*90)
print(b)
print("-"*90)
print(a*b)

[[0]
 [1]
 [2]
 [3]]
------------------------------------------------------------------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------------------------------------------------------------------
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [27 30 33]]


In [67]:
a  = np.arange(2).reshape(2,1)
b = np.arange(3).reshape(1,3)
print(a+b)

[[0 1 2]
 [1 2 3]]


In [68]:
## np.sort
np.random.seed(42)
a = np.random.randint(10,20,10)
a

array([16, 13, 17, 14, 16, 19, 12, 16, 17, 14])